# Generated by Django 6.0.1 on 2026-01-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_employee_role_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='custom_check_in_time',
            field=models.TimeField(blank=True, help_text='Custom check-in time', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='custom_check_out_time',
            field=models.TimeField(blank=True, help_text='Custom check-out time', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='custom_full_day_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom full day hours', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='custom_half_day_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom half day hours', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='use_custom_hours',
            field=models.BooleanField(default=False, help_text='Use custom working hours instead of default'),
        ),
    ]
