# Generated by Django 6.0.1 on 2026-01-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='checkin_method',
            field=models.CharField(choices=[('SELF', 'Self Check-in'), ('ADMIN', 'Admin Tracking'), ('MANUAL', 'Manual Entry')], default='ADMIN', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
