# Generated by Django 6.0.1 on 2026-01-19 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancerecord_checkin_method_and_more'),
        ('enrollment', '0003_employee_role_employee_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenceTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('scan_count', models.IntegerField(default=0)),
                ('not_present_count', models.IntegerField(default=0)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('NOT_PRESENT', 'Not Present'), ('UNKNOWN', 'Not Scanned')], default='UNKNOWN', max_length=20)),
                ('auto_marked_absent', models.BooleanField(default=False)),
                ('auto_checked_out', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presence_tracking', to='enrollment.employee')),
            ],
            options={
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
